# Generated by Django 4.1 on 2022-08-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True},
        ),
    ]
