# Generated by Django 4.1 on 2022-08-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='dni',
        ),
        migrations.AlterField(
            model_name='relation',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.cliente'),
        ),
    ]
