# Generated by Django 4.1 on 2022-08-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_brand', models.TextField()),
            ],
            options={
                'db_table': 'marca_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.TextField(unique=True)),
                ('card_cvv', models.IntegerField()),
                ('card_grant_date', models.TextField()),
                ('card_expiration_date', models.TextField()),
                ('card_type', models.TextField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
