# Generated by Django 4.1 on 2022-08-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('number', models.TextField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.TextField(db_column='employee_DNI')),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('transaction_type', models.TextField()),
                ('transaction_time', models.TextField()),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.IntegerField()),
                ('branch_name', models.TextField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
    ]
